### ISSUE TITLE
Listar problemas no README

### ISSUE THREAD

**Issue by Anemaygi** [plonegovbr/portalbrasil-intranet#17]
**Descreva o que não está claro**

Esta tarefa tem como objetivo atualizar a documentação README do projeto

**Comment by Anemaygi** [comment]
1. Trocar `make check` for `make format`

**Comment by emmenezes** [comment]
2. Instalar o seguinte pacote se houver erro de `RequiredDependencyException: jpeg`
```
sudo apt install libjpeg-dev
```

3. Adicionar código de instalação do `pnpm`
```
npm install -g pnpm
```
